# =============================================
# Perfil: DESARROLLO (dev)
# =============================================

ssh.host=172.20.200.168
ssh.port=22
ssh.user=admiddle
ssh.password=M1ddL3_W4r3
ssh.scripts.path=/home/admiddle/

##########CONEXIONES GE###########
spring.datasource.ge.jdbc-url=jdbc:oracle:thin:@(DESCRIPTION =(FAILOVER = ON)(LOAD_BALANCE = on)(ADDRESS = (PROTOCOL = TCP)(HOST = 10.102.3.22)(PORT = 1521))(CONNECT_DATA =(SERVICE_NAME = FEMSADEV_FSADEPDB.paas.oracle.com)))
spring.datasource.ge.username=GESTION_OBI
spring.datasource.ge.password=GST#0932#OBI
spring.datasource.ge.driver-class-name=oracle.jdbc.OracleDriver

# H2 Console habilitada en desarrollo
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:framedb_dev
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop

# Logs detallados
logging.level.com.fybeca=DEBUG
logging.level.org.springframework=INFO
