# =============================================
# Perfil: PRUEBAS (test)
# =============================================

ssh.host=${SSH_HOST:172.20.200.100}
ssh.port=${SSH_PORT:22}
ssh.user=${SSH_USER:admiddle}
ssh.password=${SSH_PASSWORD:}
ssh.scripts.path=${SSH_SCRIPTS_PATH:/home/admiddle/}

##########CONEXIONES GE###########
spring.datasource.ge.jdbc-url=${GE_JDBC_URL:jdbc:oracle:thin:@(DESCRIPTION =(FAILOVER = ON)(LOAD_BALANCE = on)(ADDRESS = (PROTOCOL = TCP)(HOST = 10.102.3.22)(PORT = 1521))(CONNECT_DATA =(SERVICE_NAME = FEMSADEV_FSADEPDB.paas.oracle.com)))}
spring.datasource.ge.username=${GE_USERNAME:GESTION_OBI}
spring.datasource.ge.password=${GE_PASSWORD:}
spring.datasource.ge.driver-class-name=oracle.jdbc.OracleDriver

# H2 en memoria para pruebas
spring.h2.console.enabled=false
spring.datasource.url=jdbc:h2:mem:framedb_test
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop

# Logs moderados
logging.level.com.fybeca=INFO
logging.level.org.springframework=WARN
